name: CRM_EXPO Native CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: node:22

    steps:
      - uses: actions/checkout@v4

      - run: npm ci

      - run: npm test

     